Best js practices Peer feedback
jeanbuhendwa/Peer-feedback-js pull request #1
Opened 2023-02-27 13:43 UTC by jeanbuhendwa

## Best JavaScript Peer Feedback 

In this pull request, I have : 

- [ ] Added src folder with the `index.html`, `index.js`, `style.css` and all the `modules` used in this project 
- [ ] Added the linters check for `css` `html` and `Js` 
- [ ] Configured the webpack

2023-02-27 16:03 UTC, yodit93 requested changes
Hello @jeanbuhendwa 
Good work for implementing the Todo List project for review.✅
-  No Linter errors ✔️ 

#Changes required ♻️ 
Please consider all comments below to improve your code.
Thank you 👍

2023-02-27 16:03 UTC, yodit93 commented on src/modules/task.js
> +let listArr;
Please avoid using global variables. in order to implement the best java script practices. Instead of this you can declare variables inside a function or class.

2023-02-27 16:03 UTC, yodit93 commented on src/modules/task.js
> +}
I suggest to re-write those lines of code in a simple and smart way, (KISS) following the best java script practice to make your code easy to understand.

for example:  You can say:

listArr = JSON.parse(storedData) || [];

2023-02-27 16:03 UTC, yodit93 commented on src/modules/task.js
> +  localStorage.setItem('Todo', JSON.stringify(listArr));
Please avoid the repetition of lines of code. You can create a function for saving your list on the local storage and you call it whenever you need it. This makes your code DRY and easly understandable.

2023-02-27 16:03 UTC, yodit93 commented on src/modules/task.js
> +const clearAll = document.getElementById('reset-all');
I recommend you declare all your variables at the top of your code as much as possible for easy access and for avoiding accidental reassignment.

2023-02-27 16:03 UTC, yodit93 commented on src/modules/taskStatus.js
> +
I suggest you not leave space between the lines for better readability.

2023-03-03 05:48 UTC, jeanbuhendwa commented
Thanks @yodit93 for the feedback 
I have worked on them.

2023-03-03 05:48 UTC, merged